// WordPress webpack config.
const defaultConfig = require("@wordpress/scripts/config/webpack.config");

// Plugins.
const RemoveEmptyScriptsPlugin = require("webpack-remove-empty-scripts");

// Utilities
const path = require("path");

// Add any new entry points by extending the webpack config.
module.exports = {
  ...defaultConfig,
  ...{
    entry: {
      editor: path.resolve(process.cwd(), "resources/js", "editor.js"),
      "block-styles": path.resolve(
        process.cwd(),
        "resources/js",
        "block-styles.js",
      ),
      "block-variations": path.resolve(
        process.cwd(),
        "resources/js",
        "block-variations.js",
      ),
      "mixin-styles-gb-scripts": path.resolve(
        process.cwd(),
        "resources/js",
        "mixin-styles-gb-scripts.js",
      ),
      "mixin-styles-gb-contrast": path.resolve(
        process.cwd(),
        "resources/js",
        "mixin-styles-gb-contrast.js",
      ),
    },
    plugins: [
      // Include WP's plugin config.
      ...defaultConfig.plugins,

      // Removes the empty `.js` files generated by webpack but
      // set it after WP has generated its `*.asset.php` file.
      new RemoveEmptyScriptsPlugin({
        stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
      }),
    ],
  },
};
